SUPABASE_URL = "https://txzebloazeqpyxewvqan.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4emVibG9hemVxcHl4ZXd2cWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NjA4NzQsImV4cCI6MjA4NTMzNjg3NH0.A2RH1gIX_48rFwXcKPDKw5K_8USxPXLt-r-A3neXMKg"
